title: Matt Gerig # your name (or website title) here
logo: "https://github.com/mattg629/MattGerigGIS.github.io/blob/master/images/IMG_20210522_115020977_HDR%20(2).jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  GIS Analyst Manager Curious Wanderer 
  <br><br>
  <a href="https://www.linkedin.com/in/matt-gerig-629b329/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
